export default [
  {
    name: "Flash point",
    verified: "afen",
    description: "",
    governmentAuthority: "Nigeria",
    hightestBid: 2.9,
    price: 3.1,
    auction: true,
    expires: "",
    owner: { name: "Curtis Flores", description: "" },
    created: "",
    royalties: {},
    likes: 10,
    bids: [
      {
        name: "",
        bidAmount: 2.9,
      },
      {
        name: "",
        bidAmount: 2.18,
      },
    ],
  },
  {
    name: "Flash point",
    verified: "afen",
    description: "",
    governmentAuthority: "Nigeria",
    hightestBid: 2.9,
    price: 3.1,
    auction: true,
    expires: "",
    owner: { name: "Curtis Flores", description: "" },
    created: "",
    royalties: {},
    likes: 10,
    bids: [
      {
        name: "",
        bidAmount: 2.9,
      },
      {
        name: "",
        bidAmount: 2.18,
      },
    ],
  },
  {
    name: "Flash point",
    verified: "afen",
    description: "",
    governmentAuthority: "Nigeria",
    hightestBid: 2.9,
    price: 3.1,
    auction: true,
    expires: "",
    owner: { name: "Curtis Flores", description: "" },
    created: "",
    royalties: {},
    likes: 10,
    bids: [
      {
        name: "",
        bidAmount: 2.9,
      },
      {
        name: "",
        bidAmount: 2.18,
      },
    ],
  },
  {
    name: "Flash point",
    verified: "afen",
    description: "",
    governmentAuthority: "Nigeria",
    hightestBid: 2.9,
    price: 3.1,
    auction: true,
    expires: "",
    owner: { name: "Curtis Flores", description: "" },
    created: "",
    royalties: {},
    likes: 10,
    bids: [
      {
        name: "",
        bidAmount: 2.9,
      },
      {
        name: "",
        bidAmount: 2.18,
      },
    ],
  },
  {
    name: "Flash point",
    verified: "afen",
    description: "",
    governmentAuthority: "Nigeria",
    hightestBid: 2.9,
    price: 3.1,
    auction: true,
    expires: "",
    owner: { name: "Curtis Flores", description: "" },
    created: "",
    royalties: {},
    likes: 10,
    bids: [
      {
        name: "",
        bidAmount: 2.9,
      },
      {
        name: "",
        bidAmount: 2.18,
      },
    ],
  },
  {
    name: "Flash point",
    verified: "afen",
    description: "",
    governmentAuthority: "Nigeria",
    hightestBid: 2.9,
    price: 3.1,
    auction: true,
    expires: "",
    owner: { name: "Curtis Flores", description: "" },
    created: "",
    royalties: {},
    likes: 10,
    bids: [
      {
        name: "",
        bidAmount: 2.9,
      },
      {
        name: "",
        bidAmount: 2.18,
      },
    ],
  },
  {
    name: "Flash point",
    verified: "afen",
    description: "",
    governmentAuthority: "Nigeria",
    hightestBid: 2.9,
    price: 3.1,
    auction: true,
    expires: "",
    owner: { name: "Curtis Flores", description: "" },
    created: "",
    royalties: {},
    likes: 10,
    bids: [
      {
        name: "",
        bidAmount: 2.9,
      },
      {
        name: "",
        bidAmount: 2.18,
      },
    ],
  },
  {
    name: "Flash point",
    verified: "afen",
    description: "",
    governmentAuthority: "Nigeria",
    hightestBid: 2.9,
    price: 3.1,
    auction: true,
    expires: "",
    owner: { name: "Curtis Flores", description: "" },
    created: "",
    royalties: {},
    likes: 10,
    bids: [
      {
        name: "",
        bidAmount: 2.9,
      },
      {
        name: "",
        bidAmount: 2.18,
      },
    ],
  },
  {
    name: "Flash point",
    verified: "afen",
    description: "",
    governmentAuthority: "Nigeria",
    hightestBid: 2.9,
    price: 3.1,
    auction: true,
    expires: "",
    owner: { name: "Curtis Flores", description: "" },
    created: "",
    royalties: {},
    likes: 10,
    bids: [
      {
        name: "",
        bidAmount: 2.9,
      },
      {
        name: "",
        bidAmount: 2.18,
      },
    ],
  },
  {
    name: "Flash point",
    verified: "government",
    description: "",
    governmentAuthority: "Nigeria",
    hightestBid: 2.9,
    price: 3.1,
    auction: true,
    expires: "",
    owner: { name: "Curtis Flores", description: "" },
    created: "",
    royalties: {},
    likes: 10,
    bids: [
      {
        name: "",
        bidAmount: 2.9,
      },
      {
        name: "",
        bidAmount: 2.18,
      },
    ],
  },
  {
    name: "Flash point",
    verified: "government",
    description: "",
    governmentAuthority: "Nigeria",
    hightestBid: 2.9,
    price: 3.1,
    auction: true,
    expires: "",
    owner: { name: "Curtis Flores", description: "" },
    created: "",
    royalties: {},
    likes: 10,
    bids: [
      {
        name: "",
        bidAmount: 2.9,
      },
      {
        name: "",
        bidAmount: 2.18,
      },
    ],
  },
  {
    name: "Flash point",
    verified: "government",
    description: "",
    governmentAuthority: "Nigeria",
    hightestBid: 2.9,
    price: 3.1,
    auction: true,
    expires: "",
    owner: { name: "Curtis Flores", description: "" },
    created: "",
    royalties: {},
    likes: 10,
    bids: [
      {
        name: "",
        bidAmount: 2.9,
      },
      {
        name: "",
        bidAmount: 2.18,
      },
    ],
  },
  {
    name: "Flash point",
    verified: "government",
    description: "",
    governmentAuthority: "Nigeria",
    hightestBid: 2.9,
    price: 3.1,
    auction: true,
    expires: "",
    owner: { name: "Curtis Flores", description: "" },
    created: "",
    royalties: {},
    likes: 10,
    bids: [
      {
        name: "",
        bidAmount: 2.9,
      },
      {
        name: "",
        bidAmount: 2.18,
      },
    ],
  },
  {
    name: "Flash point",
    verified: "government",
    description: "",
    governmentAuthority: "Nigeria",
    hightestBid: 2.9,
    price: 3.1,
    auction: true,
    expires: "",
    owner: { name: "Curtis Flores", description: "" },
    created: "",
    royalties: {},
    likes: 10,
    bids: [
      {
        name: "",
        bidAmount: 2.9,
      },
      {
        name: "",
        bidAmount: 2.18,
      },
    ],
  },
  {
    name: "Flash point",
    verified: "government",
    description: "",
    governmentAuthority: "Nigeria",
    hightestBid: 2.9,
    price: 3.1,
    auction: true,
    expires: "",
    owner: { name: "Curtis Flores", description: "" },
    created: "",
    royalties: {},
    likes: 10,
    bids: [
      {
        name: "",
        bidAmount: 2.9,
      },
      {
        name: "",
        bidAmount: 2.18,
      },
    ],
  },
  {
    name: "Flash point",
    verified: "government",
    description: "",
    governmentAuthority: "Nigeria",
    hightestBid: 2.9,
    price: 3.1,
    auction: true,
    expires: "",
    owner: { name: "Curtis Flores", description: "" },
    created: "",
    royalties: {},
    likes: 10,
    bids: [
      {
        name: "",
        bidAmount: 2.9,
      },
      {
        name: "",
        bidAmount: 2.18,
      },
    ],
  },
  {
    name: "Flash point",
    verified: "government",
    description: "",
    governmentAuthority: "Nigeria",
    hightestBid: 2.9,
    price: 3.1,
    auction: true,
    expires: "",
    owner: { name: "Curtis Flores", description: "" },
    created: "",
    royalties: {},
    likes: 10,
    bids: [
      {
        name: "",
        bidAmount: 2.9,
      },
      {
        name: "",
        bidAmount: 2.18,
      },
    ],
  },
  {
    name: "Flash point",
    verified: "government",
    description: "",
    governmentAuthority: "Nigeria",
    hightestBid: 2.9,
    price: 3.1,
    auction: true,
    expires: "",
    owner: { name: "Curtis Flores", description: "" },
    created: "",
    royalties: {},
    likes: 10,
    bids: [
      {
        name: "",
        bidAmount: 2.9,
      },
      {
        name: "",
        bidAmount: 2.18,
      },
    ],
  },
];
